--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2026.1.112.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 10. 08. 9:45:24
-- Server version: 8.0.46
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE elektro_leltar;

--
-- Drop table `komp_tul`
--
DROP TABLE IF EXISTS komp_tul;

--
-- Drop table `tulajdonsagok`
--
DROP TABLE IF EXISTS tulajdonsagok;

--
-- Drop table `komponensek`
--
DROP TABLE IF EXISTS komponensek;

--
-- Drop table `szekreny`
--
DROP TABLE IF EXISTS szekreny;

--
-- Set default database
--
USE elektro_leltar;

--
-- Create table `szekreny`
--
CREATE TABLE szekreny (
  id int NOT NULL AUTO_INCREMENT,
  nev varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `komponensek`
--
CREATE TABLE komponensek (
  id int NOT NULL AUTO_INCREMENT,
  szekreny_id int NOT NULL,
  sor int NOT NULL,
  oszlop int NOT NULL,
  nev varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE komponensek
ADD CONSTRAINT FK_komponensek_szekreny_id FOREIGN KEY (szekreny_id)
REFERENCES szekreny (id);

--
-- Create table `tulajdonsagok`
--
CREATE TABLE tulajdonsagok (
  id int NOT NULL AUTO_INCREMENT,
  nev varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `komp_tul`
--
CREATE TABLE komp_tul (
  id int NOT NULL AUTO_INCREMENT,
  komp_id int NOT NULL,
  tul_id int NOT NULL,
  ertek varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE komp_tul
ADD CONSTRAINT FK_komp_tul_komp_id FOREIGN KEY (komp_id)
REFERENCES komponensek (id);

--
-- Create foreign key
--
ALTER TABLE komp_tul
ADD CONSTRAINT FK_komp_tul_tul_id FOREIGN KEY (tul_id)
REFERENCES tulajdonsagok (id);

-- 
-- Dumping data for table szekreny
--
INSERT INTO szekreny(id, nev) VALUES
(1, 'Bal'),
(2, 'Jobb'),
(3, 'Szekrény');

-- 
-- Dumping data for table tulajdonsagok
--
INSERT INTO tulajdonsagok(id, nev) VALUES
(1, 'Amper'),
(2, 'Volt'),
(3, 'Ohm'),
(4, 'Watt'),
(5, 'Szín'),
(6, 'Fahrad');

-- 
-- Dumping data for table komponensek
--
INSERT INTO komponensek(id, szekreny_id, sor, oszlop, nev) VALUES
(1, 1, 6, 7, 'LED'),
(2, 2, 2, 4, 'Ellenállás'),
(3, 3, 1, 5, 'Kondenzátor');

-- 
-- Dumping data for table komp_tul
--
INSERT INTO komp_tul(id, komp_id, tul_id, ertek) VALUES
(1, 1, 5, 'Piros'),
(2, 2, 3, '25'),
(3, 3, 6, '0.1'),
(4, 1, 2, '1.5'),
(5, 1, 1, '0.013');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;